PROGRAM=bbproxy
LIBDIR=lib64
CFLAGS=-m64
CFLAGS+=-Wall -std=c99 -pedantic
CFLAGS+=`pkg-config --cflags json`
CFLAGS+=`pkg-config --cflags libcrypto`
CFLAGS+=`pkg-config --cflags zlib`
LDLIBS=-ldl
LDLIBS+=json/$(LIBDIR)/libjson.a
LDLIBS+=/usr/$(LIBDIR)/libcrypto.a
LDLIBS+=/usr/$(LIBDIR)/libz.a

default: $(PROGRAM)

$(PROGRAM): *.c

clean:
	rm -f $(PROGRAM)
