PROGRAM=bbproxy
LIBDIR=lib
CFLAGS=-m32
CFLAGS+=-Wall -std=c99 -pedantic
CFLAGS+=-I./json/json-c-0.10.i686/
CFLAGS+=`pkg-config --cflags libcrypto`
CFLAGS+=`pkg-config --cflags zlib`
LDLIBS=-ldl
LDLIBS+=./json/json-c-0.10.i686/.libs/libjson.a
LDLIBS+=/usr/$(LIBDIR)/libcrypto.a
LDLIBS+=/usr/$(LIBDIR)/libz.a

default: $(PROGRAM)

$(PROGRAM): *.c

clean:
	rm -f $(PROGRAM)
