PROGRAM=bbproxy
LIBDIR=lib64
CFLAGS=-m64
CFLAGS+=-Wall -std=c99 -pedantic
CFLAGS+=-I./json/json-c-0.10.x86_64/
CFLAGS+=`pkg-config --cflags libcrypto`
CFLAGS+=`pkg-config --cflags zlib`
LDLIBS=-ldl
LDLIBS+=./json/json-c-0.10.x86_64/.libs/libjson.a
LDLIBS+=/usr/$(LIBDIR)/libcrypto.a
LDLIBS+=/usr/$(LIBDIR)/libz.a

default: $(PROGRAM)

$(PROGRAM): *.c

clean:
	rm -f $(PROGRAM)
